# Generated by Django 6.0.4 on 2026-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('form', models.FloatField()),
                ('total_points', models.IntegerField(default=0)),
                ('draft_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
