# Generated by Django 6.0.4 on 2026-04-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
